# Generated by Django 5.2 on 2025-07-03 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('create_agent', '0007_agentintegrationsfrontend_frontendintegrationclient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(help_text='Primary key for the team.', primary_key=True, serialize=False)),
                ('team_name', models.CharField(help_text='Name of the team.', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the team is active.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether the team is deleted.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the team was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the team was updated.')),
                ('meta_data', models.JSONField(blank=True, help_text='Additional metadata for the team.', null=True)),
                ('agents', models.ManyToManyField(blank=True, help_text='Agents in the team.', related_name='teams', to='create_agent.agent')),
                ('user', models.ForeignKey(help_text='The user this team belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('team_member_id', models.AutoField(help_text='Primary key for the team member.', primary_key=True, serialize=False)),
                ('team_member_name', models.CharField(help_text='Name of the team member.', max_length=255)),
                ('team_member_email', models.EmailField(help_text='Email of the team member.', max_length=255)),
                ('team_member_role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', help_text='Role of the team member.', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the team member is active.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether the team member is deleted.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the team member was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the team member was updated.')),
                ('meta_data', models.JSONField(blank=True, help_text='Additional metadata for the team member.', null=True)),
                ('team', models.ForeignKey(help_text='The team this team member belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='accounts.team')),
                ('user', models.ForeignKey(help_text='The user this team member belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['user', 'is_active'], name='accounts_te_user_id_3de7e1_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['team_name'], name='accounts_te_team_na_4d46c6_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['created_at'], name='accounts_te_created_34c800_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['team', 'is_active'], name='accounts_te_team_id_8b1ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['team_member_email'], name='accounts_te_team_me_6eb22f_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['team_member_role'], name='accounts_te_team_me_ccf8be_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['created_at'], name='accounts_te_created_a17dc9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'team_member_email')},
        ),
    ]
