# Generated by Django 5.2 on 2025-07-04 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_team_teammember_team_accounts_te_user_id_3de7e1_idx_and_more'),
        ('create_agent', '0007_agentintegrationsfrontend_frontendintegrationclient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='agents',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='user',
        ),
        migrations.CreateModel(
            name='TeamAgent',
            fields=[
                ('team_agent_id', models.AutoField(help_text='Primary key for the team agent.', primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the team agent is active.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether the team agent is deleted.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the team agent was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the team agent was updated.')),
                ('meta_data', models.JSONField(blank=True, help_text='Additional metadata for the team agent.', null=True)),
                ('agent', models.ForeignKey(help_text='The agent this team agent belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='team_agents', to='create_agent.agent')),
                ('team', models.ForeignKey(help_text='The team this team agent belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='team_agents', to='accounts.team')),
            ],
            options={
                'verbose_name': 'Team Agent',
                'verbose_name_plural': 'Team Agents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['team', 'agent', 'is_active'], name='accounts_te_team_id_5135e7_idx'), models.Index(fields=['created_at'], name='accounts_te_created_b3492b_idx')],
                'unique_together': {('team', 'agent')},
            },
        ),
    ]
