# Generated by Django 5.2 on 2025-06-30 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_conversation_is_active_conversation_is_archived_and_more'),
        ('create_agent', '0007_agentintegrationsfrontend_frontendintegrationclient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='frontend_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frontend_client_conversations', to='create_agent.frontendintegrationclient'),
        ),
    ]
