# Generated by Django 5.2 on 2025-06-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create_agent", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agenttexts",
            old_name="text",
            new_name="text_content",
        ),
        migrations.RemoveField(
            model_name="agentdocuments",
            name="document_url",
        ),
        migrations.RemoveField(
            model_name="agentembeddings",
            name="embedding_vector",
        ),
        migrations.RemoveField(
            model_name="agentqapairs",
            name="answer",
        ),
        migrations.RemoveField(
            model_name="agentqapairs",
            name="question",
        ),
        migrations.RemoveField(
            model_name="agentvectorsdatabase",
            name="embedding_model",
        ),
        migrations.RemoveField(
            model_name="agentvectorsdatabase",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="agentvectorsdatabase",
            name="is_archived",
        ),
        migrations.RemoveField(
            model_name="agentvectorsdatabase",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="agentvectorsdatabase",
            name="storage_backend",
        ),
        migrations.RemoveField(
            model_name="agentvectorsdatabase",
            name="vector_dimension",
        ),
        migrations.AddField(
            model_name="agentdocuments",
            name="document_file",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="agentdocuments",
            name="document_path",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="agentembeddings",
            name="embedding_model_version",
            field=models.CharField(
                blank=True,
                default="text-embedding-3-small",
                help_text="Version of the embedding model (e.g., text-embedding-3-small, all-MiniLM-L6-v2, etc.).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agentintegrations",
            name="integration_content",
            field=models.TextField(
                blank=True, help_text="Content of the integration.", null=True
            ),
        ),
        migrations.AddField(
            model_name="agentqapairs",
            name="qa_content",
            field=models.TextField(
                blank=True, default=dict, help_text="QA pair content.", null=True
            ),
        ),
        migrations.AddField(
            model_name="agentvectorsdatabase",
            name="database_index",
            field=models.CharField(
                blank=True,
                help_text="Index name for the vector database.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agentvectorsdatabase",
            name="namespace",
            field=models.CharField(
                blank=True,
                help_text="Namespace for the index in the vector database.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agentvectorsdatabase",
            name="vdb_name",
            field=models.CharField(
                default="pinecone",
                help_text="Name of the vector database where vectors are stored (e.g., FAISS, Pinecone, Chroma, Weaviate).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="agentwebsites",
            name="website_content",
            field=models.TextField(
                blank=True, help_text="Content of the website.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="agentembeddings",
            name="embedding_model",
            field=models.CharField(
                blank=True,
                default="openai-ada",
                help_text="Name of the embedding model (e.g., openai-ada, sentence-transformers, etc.).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agentembeddings",
            name="object_id",
            field=models.IntegerField(
                blank=True,
                help_text="ID of the object (e.g., document, text, etc.).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agentembeddings",
            name="similarity_score",
            field=models.FloatField(
                blank=True,
                default=0.0,
                help_text="Similarity score with respect to a query vector.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agentembeddings",
            name="vector_dimension",
            field=models.IntegerField(
                blank=True,
                default=1536,
                help_text="Dimension of the embedding vector.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agentvectorsdatabase",
            name="database_path",
            field=models.CharField(
                blank=True,
                help_text="Path to the vector database.",
                max_length=255,
                null=True,
            ),
        ),
    ]
