# Generated by Django 5.2 on 2025-06-10 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("create_agent", "0002_rename_text_agenttexts_text_content_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agenttexts",
            old_name="text_name",
            new_name="text_title",
        ),
    ]
