# Generated by Django 5.2 on 2025-06-17 17:15

import django.core.files.storage
import django.db.models.deletion
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create_agent", "0003_rename_text_name_agenttexts_text_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agentdocuments",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Agent Document",
                "verbose_name_plural": "Agent Documents",
            },
        ),
        migrations.AddField(
            model_name="agentdocuments",
            name="embedded",
            field=models.BooleanField(
                default=False, help_text="Whether the document has been embedded."
            ),
        ),
        migrations.AddField(
            model_name="agentembeddings",
            name="num_chunks",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Number of chunks in the embedding.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agentintegrations",
            name="embedded",
            field=models.BooleanField(
                default=False, help_text="Whether the integration has been embedded."
            ),
        ),
        migrations.AddField(
            model_name="agenttexts",
            name="embedded",
            field=models.BooleanField(
                default=False, help_text="Whether the text has been embedded."
            ),
        ),
        migrations.AddField(
            model_name="agentwebsites",
            name="embedded",
            field=models.BooleanField(
                default=False, help_text="Whether the website has been embedded."
            ),
        ),
        migrations.AlterField(
            model_name="agentdocuments",
            name="agent",
            field=models.ForeignKey(
                help_text="The agent this document belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="create_agent.agent",
            ),
        ),
        migrations.AlterField(
            model_name="agentdocuments",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the document was created."
            ),
        ),
        migrations.AlterField(
            model_name="agentdocuments",
            name="document_description",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of the document's contents.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agentdocuments",
            name="document_file",
            field=models.FileField(
                blank=True,
                help_text="The actual document file.",
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PureWindowsPath(
                        "C:/Users/hp/Documents/chatbot_django/bot/media"
                    )
                ),
                upload_to="documents/",
            ),
        ),
        migrations.AlterField(
            model_name="agentdocuments",
            name="document_format",
            field=models.CharField(
                blank=True,
                help_text="Format of the document (e.g., PDF, DOCX).",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agentdocuments",
            name="document_id",
            field=models.AutoField(
                help_text="Unique identifier for the document.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="agentdocuments",
            name="document_language",
            field=models.CharField(
                blank=True,
                help_text="Language of the document content.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agentdocuments",
            name="document_name",
            field=models.CharField(
                blank=True, help_text="Name of the document.", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="agentdocuments",
            name="document_path",
            field=models.URLField(
                blank=True,
                help_text="URL path to the document if stored externally.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agentdocuments",
            name="document_size",
            field=models.BigIntegerField(
                blank=True, help_text="Size of the document in bytes.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="agentdocuments",
            name="document_tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of tags associated with the document.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agentdocuments",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether the document is currently active."
            ),
        ),
        migrations.AlterField(
            model_name="agentdocuments",
            name="is_archived",
            field=models.BooleanField(
                default=False, help_text="Whether the document has been archived."
            ),
        ),
        migrations.AlterField(
            model_name="agentdocuments",
            name="is_deleted",
            field=models.BooleanField(
                default=False, help_text="Whether the document has been soft-deleted."
            ),
        ),
        migrations.AlterField(
            model_name="agentdocuments",
            name="meta_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional metadata about the document.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agentdocuments",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the document was last updated."
            ),
        ),
        migrations.AlterField(
            model_name="agentvectorsdatabase",
            name="database_index",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Index name for the vector database.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="agentdocuments",
            index=models.Index(
                fields=["agent", "document_format"],
                name="create_agen_agent_i_28af23_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentdocuments",
            index=models.Index(
                fields=["created_at"], name="create_agen_created_27f268_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentdocuments",
            index=models.Index(
                fields=["is_active", "is_deleted"],
                name="create_agen_is_acti_1eab40_idx",
            ),
        ),
    ]
