# Generated by Django 5.2 on 2025-06-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "create_agent",
            "0004_alter_agentdocuments_options_agentdocuments_embedded_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentembeddings",
            name="meta_data",
            field=models.JSONField(
                blank=True, help_text="Optional metadata for the embedding.", null=True
            ),
        ),
    ]
