# Generated by Django 5.2 on 2025-06-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("create_agent", "0005_alter_agentembeddings_meta_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agentwebsites",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Agent Website",
                "verbose_name_plural": "Agent Websites",
            },
        ),
        migrations.AlterField(
            model_name="agentembeddings",
            name="source_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Original source URL if the object was scraped or fetched online.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agentwebsites",
            name="crawl_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("partial", "Partial"),
                    ("crawling", "Crawling"),
                ],
                default="pending",
                help_text='Status of crawling: e.g., "pending", "success", "failed", "partial".',
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="agentwebsites",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("automated", "Automated"),
                    ("imported", "Imported"),
                ],
                default="manual",
                help_text='Source type, e.g., "manual", "automated".',
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="agentwebsites",
            name="website_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("blog", "Blog"),
                    ("e-commerce", "E-commerce"),
                    ("portfolio", "Portfolio"),
                    ("news", "News"),
                    ("documentation", "Documentation"),
                    ("social", "Social Media"),
                    ("other", "Other"),
                ],
                help_text='Type of website, e.g., "blog", "e-commerce", "portfolio".',
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="agentwebsites",
            index=models.Index(
                fields=["agent", "is_deleted"], name="agent_websi_agent_i_8b3d3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentwebsites",
            index=models.Index(
                fields=["crawl_status", "is_active"],
                name="agent_websi_crawl_s_378afd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentwebsites",
            index=models.Index(
                fields=["last_crawled_at"], name="agent_websi_last_cr_1103da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentwebsites",
            index=models.Index(
                fields=["website_url"], name="agent_websi_website_79b4ef_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="agentwebsites",
            table="agent_websites",
        ),
    ]
