# Generated by Django 5.2 on 2025-06-30 15:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_agent', '0006_alter_agentwebsites_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentIntegrationsFrontend',
            fields=[
                ('integration_id', models.AutoField(help_text='Primary key for the integration.', primary_key=True, serialize=False)),
                ('api_key', models.CharField(blank=True, help_text='API key for the integration.', max_length=255, null=True, unique=True)),
                ('integration_name', models.CharField(blank=True, help_text='Name of the integration.', max_length=255, null=True)),
                ('integration_description', models.TextField(blank=True, help_text='Description of the integration.', null=True)),
                ('website_name', models.CharField(blank=True, help_text='Name of the website.', max_length=255, null=True)),
                ('website_domain', models.CharField(help_text='Domain of the website.', max_length=255)),
                ('website_logo', models.ImageField(blank=True, help_text='Logo of the website.', null=True, upload_to='integrations_frontend/logos/')),
                ('integration_auth_type', models.CharField(blank=True, default='JWT', help_text='Type of authentication for the integration.', max_length=255, null=True)),
                ('start_message', models.TextField(blank=True, help_text='Start message for the integration.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the integration was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the integration was last updated.')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the integration is active.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if the integration is deleted.')),
                ('meta_data', models.JSONField(blank=True, default=dict, help_text='Optional metadata for the integration.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrontendIntegrationClient',
            fields=[
                ('frontend_client_id', models.UUIDField(default=uuid.uuid4, help_text='Primary key for the client.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the client was created.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates if the client is deleted.')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the client is active.')),
            ],
        ),
        migrations.AddIndex(
            model_name='agentintegrations',
            index=models.Index(fields=['agent', 'is_active'], name='create_agen_agent_i_a7cf76_idx'),
        ),
        migrations.AddIndex(
            model_name='agentintegrations',
            index=models.Index(fields=['integration_auth_status'], name='create_agen_integra_8eb26b_idx'),
        ),
        migrations.AddIndex(
            model_name='agentintegrations',
            index=models.Index(fields=['integration_category'], name='create_agen_integra_84fdcf_idx'),
        ),
        migrations.AddField(
            model_name='agentintegrationsfrontend',
            name='agent',
            field=models.ForeignKey(help_text='The agent this integration belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='integrations_frontend', to='create_agent.agent'),
        ),
        migrations.AddField(
            model_name='frontendintegrationclient',
            name='integration',
            field=models.ForeignKey(help_text='The integration this client belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='create_agent.agentintegrationsfrontend'),
        ),
    ]
