# Generated by Django 5.2 on 2025-06-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='price_id',
            new_name='price',
        ),
    ]
