# Generated by Django 5.2 on 2025-07-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_stripetransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='integrations_usage',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='team_members_usage',
            field=models.BigIntegerField(default=0, help_text='Total team members used in this subscription period'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='widgets_usage',
            field=models.BigIntegerField(default=0, help_text='Total widgets used in this subscription period'),
        ),
    ]
