# Generated by Django 5.2 on 2025-07-06 14:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_remove_usersubscription_integrations_usage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaypalTransaction',
            fields=[
                ('transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('paypal_transaction_id', models.CharField(blank=True, help_text='Paypal transaction ID for this transaction', max_length=255, null=True, unique=True)),
                ('user_email', models.EmailField(blank=True, help_text='Email of the user who owns this transaction', max_length=255, null=True)),
                ('paypal_customer_id', models.CharField(blank=True, help_text='Paypal customer ID for this transaction', max_length=255, null=True)),
                ('transaction_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount of the transaction', max_digits=10)),
                ('transaction_currency', models.CharField(default='USD', help_text='Currency of the transaction', max_length=10)),
                ('transaction_status', models.CharField(blank=True, help_text='Status of the transaction', max_length=255, null=True)),
                ('transaction_receipt_url', models.URLField(blank=True, help_text='Receipt URL for the transaction', null=True)),
                ('transaction_metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for the transaction', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='planprice',
            name='paypal_price_id',
            field=models.CharField(blank=True, help_text='Paypal price ID for this plan', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='paypal_product_id',
            field=models.CharField(blank=True, help_text='Paypal product ID for this plan', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='paypal_subscription_id',
            field=models.CharField(blank=True, help_text='Paypal subscription ID for this subscription', max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PaypalCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_customer_id', models.CharField(blank=True, help_text='Paypal customer ID for this customer', max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this Paypal customer', on_delete=django.db.models.deletion.CASCADE, related_name='paypal_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paypal Customer',
                'verbose_name_plural': 'Paypal Customers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['paypal_customer_id'], name='plans_paypa_paypal__3dc920_idx')],
            },
        ),
    ]
