# Generated by Django 5.2 on 2025-07-06 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_paypaltransaction_planprice_paypal_price_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('resource_id', models.CharField(db_index=True, max_length=100)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.JSONField()),
                ('processing_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'processed'], name='plans_paypa_event_t_b41942_idx'), models.Index(fields=['resource_id'], name='plans_paypa_resourc_8213a0_idx'), models.Index(fields=['processed', 'created_at'], name='plans_paypa_process_b3da07_idx')],
            },
        ),
        migrations.CreateModel(
            name='PayPalSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_subscription_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('APPROVAL_PENDING', 'Approval Pending'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='APPROVAL_PENDING', max_length=20)),
                ('plan_id', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next_billing_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='plans_paypa_user_id_45562d_idx'), models.Index(fields=['paypal_subscription_id'], name='plans_paypa_paypal__19b2e2_idx'), models.Index(fields=['status', 'next_billing_time'], name='plans_paypa_status_59e669_idx')],
            },
        ),
    ]
